import { describe, expect, it } from 'vitest';
import { convertValue, parseProperties, stringifyProperties } from './serverProperties';

describe('parseProperties', () => {
  it('キーバリューペアを正しくパースする', () => {
    const content = `key1=value1
key2=value2`;
    const result = parseProperties(content);
    expect(result).toEqual({ key1: 'value1', key2: 'value2' });
  });

  it('コメント行を無視する', () => {
    const content = `# This is a comment
key=value
# Another comment`;
    const result = parseProperties(content);
    expect(result).toEqual({ key: 'value' });
  });

  it('空行を無視する', () => {
    const content = `key1=value1

key2=value2`;
    const result = parseProperties(content);
    expect(result).toEqual({ key1: 'value1', key2: 'value2' });
  });

  it('値に=を含む場合も正しくパースする', () => {
    const content = `motd=Welcome to the server=best`;
    const result = parseProperties(content);
    expect(result).toEqual({ motd: 'Welcome to the server=best' });
  });

  it('前後の空白をトリムする', () => {
    const content = `  key  =  value  `;
    const result = parseProperties(content);
    expect(result).toEqual({ key: 'value' });
  });

  it('空の入力で空オブジェクトを返す', () => {
    const result = parseProperties('');
    expect(result).toEqual({});
  });
});

describe('stringifyProperties', () => {
  it('オブジェクトをプロパティ形式に変換する', () => {
    const properties = { key1: 'value1', key2: 'value2' };
    const result = stringifyProperties(properties);
    expect(result).toContain('key1=value1');
    expect(result).toContain('key2=value2');
  });

  it('ヘッダーコメントを含む', () => {
    const properties = { key: 'value' };
    const result = stringifyProperties(properties);
    expect(result).toContain('#Minecraft server properties');
    expect(result).toContain('#Generated by MC Server Manager');
  });

  it('数値を文字列に変換する', () => {
    const properties = { port: 25565 };
    const result = stringifyProperties(properties);
    expect(result).toContain('port=25565');
  });

  it('ブール値を文字列に変換する', () => {
    const properties = { pvp: true, hardcore: false };
    const result = stringifyProperties(properties);
    expect(result).toContain('pvp=true');
    expect(result).toContain('hardcore=false');
  });

  it('キーをアルファベット順にソートする', () => {
    const properties = { z: 'last', a: 'first', m: 'middle' };
    const result = stringifyProperties(properties);
    const lines = result.split('\n').filter((line) => !line.startsWith('#') && line.includes('='));
    expect(lines[0]).toBe('a=first');
    expect(lines[1]).toBe('m=middle');
    expect(lines[2]).toBe('z=last');
  });
});

describe('convertValue', () => {
  it('trueをブール値に変換する', () => {
    expect(convertValue('true')).toBe(true);
  });

  it('falseをブール値に変換する', () => {
    expect(convertValue('false')).toBe(false);
  });

  it('整数を数値に変換する', () => {
    expect(convertValue('25565')).toBe(25565);
  });

  it('負の数を数値に変換する', () => {
    expect(convertValue('-1')).toBe(-1);
  });

  it('小数を数値に変換する', () => {
    expect(convertValue('1.5')).toBe(1.5);
  });

  it('0を数値に変換する', () => {
    expect(convertValue('0')).toBe(0);
  });

  it('空文字列をそのまま返す', () => {
    expect(convertValue('')).toBe('');
  });

  it('通常の文字列をそのまま返す', () => {
    expect(convertValue('hello world')).toBe('hello world');
  });

  it('数値で始まるが数値でない文字列をそのまま返す', () => {
    expect(convertValue('1.21.1')).toBe('1.21.1');
  });
});
