import { promises as fs } from 'node:fs';
import path from 'node:path';
import { getServerDataPath } from './config';
import {
  DEFAULT_JAVA_PORT,
  DEFAULT_LEVEL_NAME,
  DEFAULT_MAX_PLAYERS,
  DEFAULT_MAX_TICK_TIME,
  DEFAULT_MAX_WORLD_SIZE,
  DEFAULT_NETWORK_COMPRESSION,
  DEFAULT_SIMULATION_DISTANCE,
  DEFAULT_SPAWN_PROTECTION,
  DEFAULT_VIEW_DISTANCE,
} from './constants';
import { validateServerId } from './validation';

export type { PropertyCategory } from '@/types';
// 共通定義を再エクスポート
export { PROPERTY_CATEGORIES } from '@/types';

// server.properties の型定義
export interface ServerProperties {
  // ゲームプレイ設定
  difficulty: 'peaceful' | 'easy' | 'normal' | 'hard';
  gamemode: 'survival' | 'creative' | 'adventure' | 'spectator';
  hardcore: boolean;
  pvp: boolean;
  'allow-flight': boolean;
  'spawn-monsters': boolean;
  'spawn-animals': boolean;
  'spawn-npcs': boolean;

  // ワールド設定
  'level-name': string;
  'level-seed': string;
  'level-type': string;
  'generate-structures': boolean;
  'max-world-size': number;

  // サーバー設定
  'server-port': number;
  'max-players': number;
  motd: string;
  'online-mode': boolean;
  'white-list': boolean;
  'enforce-whitelist': boolean;

  // パフォーマンス設定
  'view-distance': number;
  'simulation-distance': number;
  'max-tick-time': number;
  'network-compression-threshold': number;
  'sync-chunk-writes': boolean; // Paper/Spigot: falseでI/O性能向上

  // その他
  'enable-command-block': boolean;
  'spawn-protection': number;
  'player-idle-timeout': number;
  'force-gamemode': boolean;

  // 追加のプロパティ
  [key: string]: string | number | boolean;
}

// デフォルト値（パフォーマンスを考慮した設定）
const DEFAULT_PROPERTIES: Partial<ServerProperties> = {
  // ゲームプレイ
  difficulty: 'normal',
  gamemode: 'survival',
  hardcore: false,
  pvp: true,
  'allow-flight': false,
  'spawn-monsters': true,
  'spawn-animals': true,
  'spawn-npcs': true,

  // ワールド
  'level-name': DEFAULT_LEVEL_NAME,
  'level-seed': '',
  'level-type': 'minecraft:normal',
  'generate-structures': true,
  'max-world-size': DEFAULT_MAX_WORLD_SIZE,

  // サーバー
  'server-port': DEFAULT_JAVA_PORT,
  'max-players': DEFAULT_MAX_PLAYERS,
  motd: 'A Minecraft Server',
  'online-mode': true,
  'white-list': false,
  'enforce-whitelist': false,

  // パフォーマンス
  'view-distance': DEFAULT_VIEW_DISTANCE,
  'simulation-distance': DEFAULT_SIMULATION_DISTANCE,
  'max-tick-time': DEFAULT_MAX_TICK_TIME,
  'network-compression-threshold': DEFAULT_NETWORK_COMPRESSION,
  'sync-chunk-writes': false,

  // その他
  'enable-command-block': false,
  'spawn-protection': DEFAULT_SPAWN_PROTECTION,
  'player-idle-timeout': 0,
  'force-gamemode': false,
};

// server.properties ファイルをパース
export function parseProperties(content: string): Record<string, string> {
  const properties: Record<string, string> = {};

  const lines = content.split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    // コメントと空行をスキップ
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const eqIndex = trimmed.indexOf('=');
    if (eqIndex > 0) {
      const key = trimmed.substring(0, eqIndex).trim();
      const value = trimmed.substring(eqIndex + 1).trim();
      properties[key] = value;
    }
  }

  return properties;
}

// server.properties ファイルを生成
export function stringifyProperties(properties: Record<string, string | number | boolean>): string {
  const lines: string[] = [
    '#Minecraft server properties',
    `#Generated by MC Server Manager at ${new Date().toISOString()}`,
    '',
  ];

  // キーをソートして出力
  const sortedKeys = Object.keys(properties).sort();
  for (const key of sortedKeys) {
    const value = properties[key];
    lines.push(`${key}=${value}`);
  }

  return lines.join('\n');
}

// 値を適切な型に変換
export function convertValue(value: string): string | number | boolean {
  // boolean
  if (value === 'true') return true;
  if (value === 'false') return false;

  // number
  const num = Number(value);
  if (!Number.isNaN(num) && value !== '') return num;

  // string
  return value;
}

// server.properties を読み込む
export async function getServerProperties(serverId: string): Promise<ServerProperties> {
  validateServerId(serverId);

  const dataPath = getServerDataPath(serverId);
  const propertiesPath = path.join(dataPath, 'server.properties');

  try {
    const content = await fs.readFile(propertiesPath, 'utf-8');
    const rawProperties = parseProperties(content);

    // 値を適切な型に変換
    const properties: Record<string, string | number | boolean> = {};
    for (const [key, value] of Object.entries(rawProperties)) {
      properties[key] = convertValue(value);
    }

    // デフォルト値とマージ
    return { ...DEFAULT_PROPERTIES, ...properties } as ServerProperties;
  } catch {
    // ファイルが存在しない場合はデフォルト値を返す
    return DEFAULT_PROPERTIES as ServerProperties;
  }
}

// server.properties を更新
export async function updateServerProperties(
  serverId: string,
  updates: Partial<ServerProperties>
): Promise<ServerProperties> {
  validateServerId(serverId);

  const dataPath = getServerDataPath(serverId);
  const propertiesPath = path.join(dataPath, 'server.properties');

  // 既存のプロパティを読み込む
  let existingProperties: Record<string, string> = {};
  try {
    const content = await fs.readFile(propertiesPath, 'utf-8');
    existingProperties = parseProperties(content);
  } catch {
    // ファイルが存在しない場合は空のオブジェクト
  }

  // 更新を適用
  const mergedProperties: Record<string, string | number | boolean> = {
    ...existingProperties,
  };

  for (const [key, value] of Object.entries(updates)) {
    if (value !== undefined) {
      mergedProperties[key] = value;
    }
  }

  // ファイルに書き込む
  const content = stringifyProperties(mergedProperties);
  await fs.writeFile(propertiesPath, content, 'utf-8');

  // 更新後のプロパティを返す
  return getServerProperties(serverId);
}
