import yaml from 'js-yaml';
import type {
  BukkitOptimization,
  PaperGlobalOptimization,
  PaperWorldOptimization,
  PurpurOptimization,
  ServerPropertiesOptimization,
  SpigotOptimization,
} from '@/types/optimization';

/**
 * server.properties の最適化設定を生成
 * 注意: server.properties は itzg/minecraft-server が環境変数から生成するため、
 * 通常はこの関数を使用せず、docker-compose.yml の環境変数で設定する
 */
export function generateServerProperties(config: ServerPropertiesOptimization): string {
  const lines: string[] = [
    '# Optimized server.properties',
    '# Generated by mc-server optimization system',
    '',
    `sync-chunk-writes=${config.syncChunkWrites}`,
    `network-compression-threshold=${config.networkCompressionThreshold}`,
  ];
  return lines.join('\n');
}

/**
 * bukkit.yml を生成
 */
export function generateBukkitYml(config: BukkitOptimization): string {
  const data = {
    'spawn-limits': {
      monsters: config.spawnLimits.monsters,
      animals: config.spawnLimits.animals,
      'water-animals': config.spawnLimits.waterAnimals,
      'water-ambient': config.spawnLimits.waterAmbient,
      'water-underground-creature': config.spawnLimits.waterUndergroundCreature,
      axolotls: config.spawnLimits.axolotls,
      ambient: config.spawnLimits.ambient,
    },
    'ticks-per': {
      'animal-spawns': config.ticksPer.animalSpawns,
      'monster-spawns': config.ticksPer.monsterSpawns,
      'water-spawns': config.ticksPer.waterSpawns,
      'water-ambient-spawns': config.ticksPer.waterAmbientSpawns,
      'water-underground-creature-spawns': config.ticksPer.waterUndergroundCreatureSpawns,
      'axolotl-spawns': config.ticksPer.axolotlSpawns,
      'ambient-spawns': config.ticksPer.ambientSpawns,
      autosave: config.ticksPer.autosave,
    },
  };

  return `# Optimized bukkit.yml\n# Generated by mc-server optimization system\n\n${yaml.dump(data, { lineWidth: -1 })}`;
}

/**
 * spigot.yml を生成
 */
export function generateSpigotYml(config: SpigotOptimization): string {
  const data = {
    'world-settings': {
      default: {
        'merge-radius': {
          item: config.worldSettings.mergeRadius.item,
          exp: config.worldSettings.mergeRadius.exp,
        },
        'mob-spawn-range': config.worldSettings.mobSpawnRange,
        'entity-activation-range': {
          animals: config.worldSettings.entityActivationRange.animals,
          monsters: config.worldSettings.entityActivationRange.monsters,
          raiders: config.worldSettings.entityActivationRange.raiders,
          misc: config.worldSettings.entityActivationRange.misc,
          water: config.worldSettings.entityActivationRange.water,
          villagers: config.worldSettings.entityActivationRange.villagers,
          'flying-monsters': config.worldSettings.entityActivationRange.flyingMonsters,
        },
        'tick-inactive-villagers': config.worldSettings.tickInactiveVillagers,
        nerf: {
          'spawner-spawned-mobs-have-no-ai': config.worldSettings.nerf.spawnedMobsHaveNoAi,
        },
      },
    },
  };

  return `# Optimized spigot.yml\n# Generated by mc-server optimization system\n\n${yaml.dump(data, { lineWidth: -1 })}`;
}

/**
 * paper-world-defaults.yml を生成
 */
export function generatePaperWorldDefaults(config: PaperWorldOptimization): string {
  const data = {
    _version: 31,
    chunks: {
      'auto-save-interval': config.chunks.autoSaveInterval,
      'max-auto-save-chunks-per-tick': config.chunks.maxAutoSaveChunksPerTick,
      'prevent-moving-into-unloaded-chunks': config.chunks.preventMovingIntoUnloadedChunks,
      'delay-chunk-unloads-by': config.chunks.delayChunkUnloadsBy,
    },
    entities: {
      'armor-stands': {
        'do-collision-entity-lookups': config.entities.armorStands.doCollisionEntityLookups,
        tick: config.entities.armorStands.tick,
      },
      spawning: {
        'despawn-ranges': {
          ambient: {
            soft: config.entities.spawning.despawnRanges.soft,
            hard: config.entities.spawning.despawnRanges.hard,
          },
          axolotls: {
            soft: config.entities.spawning.despawnRanges.soft,
            hard: config.entities.spawning.despawnRanges.hard,
          },
          creature: {
            soft: config.entities.spawning.despawnRanges.soft,
            hard: config.entities.spawning.despawnRanges.hard,
          },
          misc: {
            soft: config.entities.spawning.despawnRanges.soft,
            hard: config.entities.spawning.despawnRanges.hard,
          },
          monster: {
            soft: config.entities.spawning.despawnRanges.soft,
            hard: config.entities.spawning.despawnRanges.hard,
          },
          underground_water_creature: {
            soft: config.entities.spawning.despawnRanges.soft,
            hard: config.entities.spawning.despawnRanges.hard,
          },
          water_ambient: {
            soft: config.entities.spawning.despawnRanges.soft,
            hard: config.entities.spawning.despawnRanges.hard,
          },
          water_creature: {
            soft: config.entities.spawning.despawnRanges.soft,
            hard: config.entities.spawning.despawnRanges.hard,
          },
        },
        'per-player-mob-spawns': config.entities.spawning.perPlayerMobSpawns,
        'scan-for-legacy-ender-dragon': config.entities.spawning.scanForLegacyEnderDragon,
      },
    },
    environment: {
      'optimize-explosions': config.environment.optimizeExplosions,
      'treasure-maps': {
        enabled: config.environment.treasureMaps.enabled,
        'find-already-discovered-loot-tables':
          config.environment.treasureMaps.findAlreadyDiscoveredLootTables,
        'find-already-discovered-villager-trade-loot-tables':
          config.environment.treasureMaps.findAlreadyDiscoveredVillagerTradeLootTables,
      },
      'water-over-lava-flow-speed': config.environment.waterOverLavaFlowSpeed,
    },
    hopper: {
      'cooldown-when-full': config.hopper.cooldownWhenFull,
      'disable-move-event': config.hopper.disableMoveEvent,
      'ignore-occluding-blocks': config.hopper.ignoreOccludingBlocks,
    },
    collisions: {
      'max-entity-collisions': config.collisions.maxEntityCollisions,
      'fix-climbing-bypassing-cramming-rule': config.collisions.fixClimbingBypassingCrammingRule,
    },
    misc: {
      'redstone-implementation': config.misc.redstoneImplementation,
      'update-pathfinding-on-block-update': config.misc.updatePathfindingOnBlockUpdate,
    },
  };

  return `# Optimized paper-world-defaults.yml\n# Generated by mc-server optimization system\n\n${yaml.dump(data, { lineWidth: -1 })}`;
}

/**
 * paper-global.yml を生成
 */
export function generatePaperGlobal(config: PaperGlobalOptimization): string {
  const data = {
    _version: 29,
    'chunk-loading': {
      'auto-config-send-distance': config.chunkLoading.autoConfigSendDistance,
      'enable-frustum-priority': config.chunkLoading.enableFrustumPriority,
      'global-max-chunk-load-rate': config.chunkLoading.globalMaxChunkLoadRate,
      'global-max-chunk-send-rate': config.chunkLoading.globalMaxChunkSendRate,
      'global-max-concurrent-loads': config.chunkLoading.globalMaxConcurrentLoads,
      'max-concurrent-sends': config.chunkLoading.maxConcurrentSends,
      'min-load-radius': config.chunkLoading.minLoadRadius,
      'player-max-chunk-load-rate': config.chunkLoading.playerMaxChunkLoadRate,
      'player-max-concurrent-loads': config.chunkLoading.playerMaxConcurrentLoads,
      'target-player-chunk-send-rate': config.chunkLoading.targetPlayerChunkSendRate,
    },
    'item-validation': {
      'display-name': config.itemValidation.displayName,
      'loc-name': config.itemValidation.locName,
      'lore-line': config.itemValidation.loreLineLength,
      book: {
        title: config.itemValidation.bookTitle,
        author: config.itemValidation.bookAuthor,
        page: config.itemValidation.bookPageLength,
        'max-pages': config.itemValidation.bookMaxPages,
      },
    },
    'packet-limiter': {
      'all-packets': {
        interval: config.packetLimiter.allPackets.interval,
        'max-packet-rate': config.packetLimiter.allPackets.maxPacketRate,
      },
    },
    misc: {
      'max-joins-per-tick': config.misc.maxJoinsPerTick,
      'region-file-cache-size': config.misc.regionFileCacheSize,
      'use-alternative-luck-formula': config.misc.useAlternativeLuckFormula,
      'lag-compensate-block-breaking': config.misc.lagCompensateBlockBreaking,
    },
  };

  return `# Optimized paper-global.yml\n# Generated by mc-server optimization system\n\n${yaml.dump(data, { lineWidth: -1 })}`;
}

/**
 * purpur.yml を生成
 */
export function generatePurpurYml(config: PurpurOptimization): string {
  const data = {
    settings: {
      'use-alternate-keepalive': config.settings.useAlternateKeepAlive,
      tps_bar: {
        enabled: config.settings.tpsBarEnabled,
      },
      'lagging-threshold': config.settings.laggingThreshold,
    },
    'world-settings': {
      default: {
        gameplay: {
          'arrow-movement': {
            'reset-despawn-counter':
              config.worldSettings.gameplay.arrowMovement.resetDespawnCounter,
          },
          'use-better-mending': config.worldSettings.gameplay.useBetterMending,
        },
        mobs: {
          villager: {
            'brain-ticks': config.worldSettings.mobs.villager.brainTicks,
            'spawn-iron-golem': {
              radius: config.worldSettings.mobs.villager.spawnIronGolemRadius,
            },
          },
          zombie: {
            'aggressive-towards-villager-when-lagging':
              config.worldSettings.mobs.zombie.aggressiveTowardsVillagerWhenLagging,
          },
        },
      },
    },
  };

  return `# Optimized purpur.yml\n# Generated by mc-server optimization system\n\n${yaml.dump(data, { lineWidth: -1 })}`;
}
